name: Produce Poll Wrappers
on:
    workflow_dispatch

jobs:

  core-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change to technical folder
        run: cd technical

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run:  python -m parenttext_pipeline.cli pull_data compile_flows

      - name: Publish poll_wrappers.json
        uses: actions/upload-artifact@v3
        with:
          name: Poll Wrappers File
          path: output/poll_wrappers.json